[general]
# Set to 'false' to disable the hook
enable = true
# Whether the hook should export your class (skill level) or not
export_class = true
# Whether the hook should should inject your Tachi PBs in place of Cloud PBs
inject_cloud_pbs = true
# Timeout for web requests, in milliseconds
timeout = 3000

[tachi]
# Tachi instance base URL
base_url = 'https://kamaitachi.xyz/'
# Tachi status endpoint
status = '/api/v1/status'
# Tachi score import endpoint
import = '/ir/direct-manual/import'
# Tachi pbs endpoint
pbs = '/api/v1/users/{}/games/sdvx/Single/pbs/all'

# The Tachi API key to use for any card
# If you only want specific cards to be recognized, omit this default entry
[cards.default]
api_key = 'your-key-here'

# Example of a specific card entry
# [cards.'E000000001']
# api_key = 'another-key-here'